- id: depth
  name: Depth
  units: meters

- id: temperature
  name: Temperature
  units: degrees

- id: voltage
  name: Voltage
  units: volts

- id: current
  name: Current
  units: ampere

- id: ax
  name: ax
  units: ms2

- id: ay
  name: ay
  units: ms2